### ISSUE TITLE
Whole earth temporal mosaics

### ISSUE THREAD

**Issue by jo-chemla** [corentin-dfg/Satellite-Image-Time-Series-Datasets#1]
Hi there, 
 - a few whole-earth mosaics with temporal parameter listed in this [twitter thread](https://twitter.com/jo_chemla/status/1656686529245224961) - actually looking for more up-to-date/complete datasets via this thread. Not always useful for research purposes, but might be useful to add Planet-basemaps monthly (2016-01 - present), Google Earth timelapse (1984-2020 from landsat/sentinel) or ESA WorldCover (sentinel 2020, 2021). 
 - also a few other examples, less for EO, in this [qgis feature request](https://github.com/qgis/QGIS/issues/51939)

**Comment by corentin-dfg** [comment]
Hello,
Thank you for your message. We are indeed looking for pre-processed datasets that are ready to be downloaded. However, the links you shared are certainly a great source of data to build your own dataset. Some countries also share annual data on their crops per parcel that may be useful for creating temporal datasets like those used in [BreizhCrops](https://isprs-archives.copernicus.org/articles/XLIII-B2-2020/1545/2020/isprs-archives-XLIII-B2-2020-1545-2020.pdf).
